/**
 * Northern Rangelands Trust (NRT) – 14 conservancies in the Northern Kenya
 * Rangeland Carbon Project (Verra VCS 1468). Data sources: land area from
 * northernkenyacommunitycarbon.org/where-we-work and NRT/seraconservancy;
 * first payment from NRT Carbon Project Impact (Feb 2022). Per-cycle carbon
 * sold, amount received and spending not publicly disclosed → N/A.
 */
window.NRT_CONSERVANCIES = [
  { id: 'sera', name: 'Sera', lat: 1.45, lng: 37.02, landHectares: 339540, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'kalama', name: 'Kalama', lat: 1.18, lng: 36.82, landHectares: 49588, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'namunyak', name: 'Namunyak', lat: 0.95, lng: 37.52, landHectares: 344000, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'west-gate', name: 'Westgate', lat: 0.82, lng: 37.18, landHectares: 4494, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'il-ngwesi', name: 'Il N\'gwesi', lat: 0.12, lng: 37.28, landHectares: 2137, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'naibunga', name: 'Naibunga', lat: 0.52, lng: 37.04, landHectares: 37990, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'lekurruki', name: 'Lekurruki', lat: 0.28, lng: 36.92, landHectares: 16866, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'melako', name: 'Melako', lat: 0.88, lng: 37.58, landHectares: 1040792, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'biliqo-bulesa', name: 'Biliqo Bulesa', lat: 1.75, lng: 37.15, landHectares: 376657, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'nasuulu', name: 'Nasuulu', lat: 0.65, lng: 37.35, landHectares: 34568, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'oldonyiro', name: 'Ol Donyiro', lat: 0.38, lng: 37.62, landHectares: null, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'meibae', name: 'Meibae', lat: 1.32, lng: 36.95, landHectares: 12235, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'nakuprat-gotu', name: 'Nakuprat-Gotu', lat: 0.58, lng: 37.68, landHectares: 72418, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null },
  { id: 'leparua', name: 'Leparua', lat: 0.42, lng: 37.58, landHectares: 33550, firstPaymentFeb2022USD: 324000, numCommunities: null, numFamilies: null, population: null, cycles: [ { period: '2013–2016', carbonSold: null, amountReceivedUSD: null, spending: null }, { period: '2017–2020', carbonSold: null, amountReceivedUSD: null, spending: null } ], yearJoined: null, status: null }
];
